laura_main = ["Dominic Toretto" ,  
"eva mendes", 
"deckard fast and furious", 
"luke evans",
"Sean Boswell",
"missandei",
"one-77"
]

mia_main = [
"jordana brewster",
"tyrese",
"Han Lue" , 
"Gisele Yashar",
"idris elba",
"Don Omar"
]

werlindo_main = [
"Luke Hobbs" , 
"Paul Walker",
"Letty fast and furious",  
"Tej Parker",
"vince fast and furious",
"jesse fast and furious" 
]

minor_char = [
"Brian OConner" ,  
"Mia Toretto" , 
"Roman Pearce" , 
"han lue fast furious", 
"suki fast and furious", 
"neela fast and furious", 
"twinkie fast and furious"]

werlindo_old = [
"tego leo fast and furious", 
"rico fast and furious", 
"elena fast and furious", 
"mister nobody fast and furious", 
"ramsey fast and furious", 
"little nobody fast and furious", 
"haddie fast and furious", 
"hector fast and furious", 
"edwin fast and furious", 
"bilkins fast and furious", 
"sargeant tanner fast and furious", 
"minka kelly"
]


laura_list = ["Dominic Toretto" ,  
"Brian OConner" ,  
"Letty fast and furious" ,  
"Mia Toretto" , 
"Roman Pearce" , 
"Tej Parker" , 
"Sean Boswell" , 
"Han Lue" , 
"Gisele Yashar" , 
"Luke Hobbs" , 
"vince fast and furious" , 
"han lue fast furious", 
"jesse fast and furious", 
"suki fast and furious", 
"deckard fast and furious", 
"monica fast and furious", 
"neela fast and furious", 
"twinkie fast and furious", 
"tego leo fast and furious", 
"rico fast and furious", 
"elena fast and furious", 
"mister nobody fast and furious", 
"ramsey fast and furious", 
"little nobody fast and furious", 
"haddie fast and furious", 
"hector fast and furious", 
"edwin fast and furious", 
"acient bilkins fast and furious", 
"sargeant tanner fast and furious", 
"minka kelly"] 

lindy_list = ["agent markham fast and furious", 
"orange julius fast and furious", 
"slap jack fast and furious", 
"jimmy fast and furious", 
"major boswell fast and furious", 
"mrs. boswell fast and furious", 
"earl fast and furious", 
"reiko fast and furious", 
"elvis fast and furious", 
"cara fast and furious", 
"agent michael stasiak fast and furious", 
"agent penning fast and furious", 
"agent sophie fast and furious", 
"agent wilkes fast and furious", 
"agent fusco fast and furious", 
"agent chato fast and furious", 
"agent macroy fast and furious", 
"rosa fast and furious", 
"jack o'conner fast and furious", 
"samantha hobbs fast and furious", 
"mondo fast and furious", 
"agent sheppard fast and furious", 
"magdalene shaw fast and furious", 
"raldo fast and furious", 
"fernando fast and furious", 
"brian marco toretto fast and furious", 
"johnny tran fast and furious", 
"carter verone fast and furious"] 

mia_list = ["d.k. takashi fast and furious", 
"arturo braga fast and furious", 
"hernan reyes fast and furious", 
"owen shaw fast and furious",
"cipher fast and furious",
"brixton lore fast and furious",
"lance nguyen fast and furious",
"enrique fast and furious",
"roberto fast and furious",
"morimoto fast and furious",
"kamata fast and furious",
"fenix calderon fast and furious",
"zizi fast and furious",
"agent riley hicks fast and furious",
"vegh fast and furious",
"klaus fast and furious",
"jah fast and furious",
"adolfson fast and furious",
"denlinger fast and furious",
"mose jakande fast and furious",
"kiet fast and furious",
"kara fast and furious",
"connor rhodes fast and furious"]

# 2019.06.18 wm -light edits
